name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
assignees: ["etdv-thevoid"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
        Please make sure there aren't any open or closed issues already for this topic before submitting.

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give a brief description of what happened and what should have happened.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information that would facilitate resolving the issue; such as logs, screenshots, scenarios in which the bug occurs, etc.
